// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwI9y2qtFpL5YB8P0Ai3kNgQDmHwJ-Xdk',
    appId: '1:903898710026:web:0a1ace30607371d62b1ff3',
    messagingSenderId: '903898710026',
    projectId: 'alamashi-app',
    authDomain: 'alamashi-app.firebaseapp.com',
    storageBucket: 'alamashi-app.firebasestorage.app',
    measurementId: 'G-4M889EZ74R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqGy-2KCwbsjeFZsIItg9wYu9nll4cnU',
    appId: '1:903898710026:android:181f15f13556976b2b1ff3',
    messagingSenderId: '903898710026',
    projectId: 'alamashi-app',
    storageBucket: 'alamashi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1I3Jun0YmnXB2DQJzrxfZnwduKj-68c',
    appId: '1:903898710026:ios:3324916484143cc32b1ff3',
    messagingSenderId: '903898710026',
    projectId: 'alamashi-app',
    storageBucket: 'alamashi-app.firebasestorage.app',
    iosBundleId: 'com.example.egyptianSupermaekat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ1I3Jun0YmnXB2DQJzrxfZnwduKj-68c',
    appId: '1:903898710026:ios:3324916484143cc32b1ff3',
    messagingSenderId: '903898710026',
    projectId: 'alamashi-app',
    storageBucket: 'alamashi-app.firebasestorage.app',
    iosBundleId: 'com.example.egyptianSupermaekat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwI9y2qtFpL5YB8P0Ai3kNgQDmHwJ-Xdk',
    appId: '1:903898710026:web:3bcf0f7f8f7fb40d2b1ff3',
    messagingSenderId: '903898710026',
    projectId: 'alamashi-app',
    authDomain: 'alamashi-app.firebaseapp.com',
    storageBucket: 'alamashi-app.firebasestorage.app',
    measurementId: 'G-ML40WP3VHX',
  );
}
